# Generated by Django 4.1.3 on 2023-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=25)),
                ('con_email', models.CharField(max_length=40)),
                ('con_phone', models.IntegerField(max_length=12)),
                ('con_message', models.CharField(max_length=500)),
            ],
        ),
    ]
