# Generated by Django 4.1.3 on 2023-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='con_phone',
            field=models.IntegerField(),
        ),
    ]
