# Generated by Django 4.1.3 on 2023-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpg', '0005_alter_ml_list_ml_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_list',
            name='ml_sno',
            field=models.IntegerField(),
        ),
    ]
